# Generated by Django 4.2.7 on 2023-11-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("status", models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
